version: '3.3'

services:
  db:
    container_name: wpMySQL
    image: arm64v8/mysql:latest
    volumes:
      - './mysql:/var/lib/mysql'
    ports:
      - '4306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: wp_site
      MYSQL_USER: wp_usr
      MYSQL_PASSWORD: wp_pass

  wordpress:
    container_name: wpSite
    depends_on:
      - db
    build: .
    # image: arm64v8/wordpress:latest
    restart: always
    ports:
      - '8000:80'
    volumes:
      - './src/themes:/var/www/html/wp-content/themes'
      - './src/plugins:/var/www/html/wp-content/plugins'
      - './src/uploads:/var/www/html/wp-content/uploads'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_usr
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp_site


